#!/usr/bin/env bash
# One-time (or refresh) setup for AIM-HI-Lab HPC — account layout as of 2026-07.
#
# Prereqs on the cluster (once per account):
#   ln -s /mnt/isilon/w_nonlri/AIM-HI-Lab ~/AIM-HI-Lab
#   Replace ~/.bashrc with the lab template (modules + ~/beegfs/env/def), then: source ~/.bashrc
#
# Run from a login or interactive node (not necessarily GPU):
#   cd ~/AIM-HI-Lab/code/jonnalr2/clarity-inference-pipeline
#   ./dev/260701_init/setup.sh
#
# Optional:
#   CLARITY_PYTORCH_CUDA=auto|cpu|cu118|cu121|cu124|cu126|skip
#   CLARITY_VENV_DIR=~/beegfs/env/clarity-inference-pipeline   # default
#   CLARITY_BEEGFS_TEMP=~/beegfs/temp                          # caches + worker scratch parent
#
set -euo pipefail

DEV_INIT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${DEV_INIT_DIR}/../.." && pwd)"

HPC_USER="${USER:-jonnalr2}"
BEEGFS_ENV_ROOT="${HOME}/beegfs/env"
BEEGFS_TEMP="${CLARITY_BEEGFS_TEMP:-${HOME}/beegfs/temp}"
VENV_DIR="${CLARITY_VENV_DIR:-${BEEGFS_ENV_ROOT}/clarity-inference-pipeline}"
AIM_HI_LAB="${HOME}/AIM-HI-Lab"

# ── Lab modules (idempotent if ~/.bashrc already loaded them) ────────────────
if ! command -v python3.12 >/dev/null 2>&1; then
  if command -v module >/dev/null 2>&1; then
    module purge 2>/dev/null || true
    module load gcc slurm git oracle/12.2.0.1 python/3.12 2>/dev/null || true
    module load cuda12.6/toolkit/12.6.2 singularity/4.2.2 2>/dev/null || true
  fi
fi

CLARITY_PYTHON="${CLARITY_PYTHON:-python3.12}"
if ! command -v "${CLARITY_PYTHON}" >/dev/null 2>&1; then
  CLARITY_PYTHON="$(command -v python3.12 2>/dev/null || command -v python3 2>/dev/null || true)"
fi
if [[ -z "${CLARITY_PYTHON}" ]]; then
  echo "Python 3.12 not found. Load modules first: source ~/.bashrc" >&2
  exit 1
fi

PYTHON_BIN="${VENV_DIR}/bin/python"
PIP_BIN="${VENV_DIR}/bin/pip"

# Scratch on BeeGFS (fast local FS); shared weights stay on AIM-HI-Lab isilon mount.
NNUNET_V1_ROOT="${BEEGFS_TEMP}/.nnunetv1"
NNUNET_V2_SCRATCH="${BEEGFS_TEMP}/.nnunetv2"
TOTALSEG_ROOT="${BEEGFS_TEMP}/.totalsegmentator"

mkdir -p "${BEEGFS_ENV_ROOT}" "${BEEGFS_TEMP}"
mkdir -p "${NNUNET_V1_ROOT}/raw" "${NNUNET_V1_ROOT}/preprocessed" "${NNUNET_V1_ROOT}/results"
mkdir -p "${NNUNET_V2_SCRATCH}/raw" "${NNUNET_V2_SCRATCH}/preprocessed" "${NNUNET_V2_SCRATCH}/results"
mkdir -p "${TOTALSEG_ROOT}"

if [[ ! -e "${AIM_HI_LAB}" ]]; then
  echo "WARNING: ${AIM_HI_LAB} does not exist." >&2
  echo "Create the lab symlink once:" >&2
  echo "  ln -s /mnt/isilon/w_nonlri/AIM-HI-Lab ~/AIM-HI-Lab" >&2
fi

cat > "${DEV_INIT_DIR}/clarity_local_env.sh" <<EOF
#!/usr/bin/env bash
# Auto-generated by dev/260701_init/setup.sh — do not edit; re-run setup.sh instead.
export CLARITY_VENV_DIR="${VENV_DIR}"
export CLARITY_BEEGFS_TEMP="${BEEGFS_TEMP}"
export CLARITY_NNUNET_V1_RAW="${NNUNET_V1_ROOT}/raw"
export CLARITY_NNUNET_V1_PREPROCESSED="${NNUNET_V1_ROOT}/preprocessed"
export CLARITY_NNUNET_V1_RESULTS="${NNUNET_V1_ROOT}/results"
export CLARITY_NNUNET_V2_RAW="${NNUNET_V2_SCRATCH}/raw"
export CLARITY_NNUNET_V2_PREPROCESSED="${NNUNET_V2_SCRATCH}/preprocessed"
export CLARITY_NNUNET_V2_RESULTS="${NNUNET_V2_SCRATCH}/results"
export TOTALSEG_HOME_DIR="${TOTALSEG_ROOT}"
export TMPDIR="\${TMPDIR:-${BEEGFS_TEMP}}"
EOF
chmod +x "${DEV_INIT_DIR}/clarity_local_env.sh"

if [[ ! -x "${PYTHON_BIN}" ]]; then
  "${CLARITY_PYTHON}" -m venv "${VENV_DIR}"
fi

"${PIP_BIN}" install --upgrade pip "setuptools<82" wheel

CLARITY_PYTORCH_CUDA="${CLARITY_PYTORCH_CUDA:-auto}"
TORCH_VARIANT=""

_install_torch_wheels() {
  local variant="$1"
  case "${variant}" in
    cpu)
      "${PIP_BIN}" install --upgrade torch torchvision --index-url "https://download.pytorch.org/whl/cpu"
      ;;
    cu118)
      "${PIP_BIN}" install --upgrade torch torchvision --index-url "https://download.pytorch.org/whl/cu118"
      ;;
    cu121)
      "${PIP_BIN}" install --upgrade torch torchvision --index-url "https://download.pytorch.org/whl/cu121"
      ;;
    cu124)
      "${PIP_BIN}" install --upgrade torch torchvision --index-url "https://download.pytorch.org/whl/cu124"
      ;;
    cu126)
      "${PIP_BIN}" install --upgrade torch torchvision --index-url "https://download.pytorch.org/whl/cu126"
      ;;
    *)
      echo "Unknown PyTorch variant: ${variant}" >&2
      exit 1
      ;;
  esac
}

if [[ "${CLARITY_PYTORCH_CUDA}" != "skip" ]]; then
  if [[ "${CLARITY_PYTORCH_CUDA}" == "auto" ]]; then
    TORCH_VARIANT="$("${PYTHON_BIN}" - <<'PY'
import re
import subprocess
import sys

def main() -> None:
    try:
        out = subprocess.check_output(["nvidia-smi"], text=True, stderr=subprocess.DEVNULL, timeout=60)
    except (FileNotFoundError, subprocess.CalledProcessError, subprocess.TimeoutExpired):
        if sys.platform == "linux":
            print("cu126")
        else:
            print("cpu")
        return
    m = re.search(r"CUDA Version:\s*(\d+)\.(\d+)", out)
    if not m:
        print("cu126")
        return
    major, minor = int(m.group(1)), int(m.group(2))
    if (major, minor) >= (12, 6):
        print("cu126")
    elif (major, minor) >= (12, 4):
        print("cu124")
    elif (major, minor) >= (12, 1):
        print("cu121")
    else:
        print("cu118")

if __name__ == "__main__":
    main()
PY
)"
  else
    TORCH_VARIANT="${CLARITY_PYTORCH_CUDA}"
  fi
  echo "CLARITY_PYTORCH_CUDA (resolved)=${TORCH_VARIANT}"
  echo "Installing torch/torchvision (${TORCH_VARIANT}) before editable install…"
  _install_torch_wheels "${TORCH_VARIANT}"
fi

echo "Installing clarity-inference-pipeline (editable) from ${REPO_ROOT}…"
"${PIP_BIN}" install -e "${REPO_ROOT}"

if [[ "${CLARITY_PYTORCH_CUDA}" != "skip" ]]; then
  echo "Re-installing torch/torchvision (${TORCH_VARIANT}) after editable install…"
  _install_torch_wheels "${TORCH_VARIANT}"
fi

"${PIP_BIN}" install TotalSegmentator nnunetv2 nnunet

# shellcheck disable=SC1091
source "${DEV_INIT_DIR}/clarity_local_env.sh"
if [[ -f "${DEV_INIT_DIR}/clarity_local_env_overrides.sh" ]]; then
  # shellcheck disable=SC1091
  source "${DEV_INIT_DIR}/clarity_local_env_overrides.sh"
fi

export PATH="${VENV_DIR}/bin:${PATH}"
export nnUNet_raw_data_base="${CLARITY_NNUNET_V1_RAW}"
export RESULTS_FOLDER="${CLARITY_NNUNET_V1_RESULTS}"
export nnUNet_raw="${CLARITY_NNUNET_V2_RAW}"
export nnUNet_preprocessed="${CLARITY_NNUNET_V2_PREPROCESSED}"
export nnUNet_results="${CLARITY_NNUNET_V2_RESULTS}"

totalseg_download_weights -t total || true

OVERRIDES_EXAMPLE="${DEV_INIT_DIR}/clarity_local_env_overrides.sh.example"
if [[ ! -f "${DEV_INIT_DIR}/clarity_local_env_overrides.sh" && -f "${OVERRIDES_EXAMPLE}" ]]; then
  echo ""
  echo "Tip: copy shared lab model paths into overrides (recommended on this cluster):"
  echo "  cp ${OVERRIDES_EXAMPLE} ${DEV_INIT_DIR}/clarity_local_env_overrides.sh"
  echo ""
fi

KITS23_MODEL_DIR="${nnUNet_results}/Dataset123_Kits23/nnUNetTrainer__nnUNetPlans__3d_fullres/fold_all"
if [[ ! -f "${KITS23_MODEL_DIR}/checkpoint_final.pth" ]]; then
  echo ""
  echo "KiTS23 v2 weights not found at:"
  echo "  ${KITS23_MODEL_DIR}/checkpoint_final.pth"
  echo "Point CLARITY_NNUNET_V2_* in clarity_local_env_overrides.sh at the lab model store,"
  echo "or install weights with nnUNetv2_install_pretrained_model_from_zip."
  echo ""
fi

echo
echo "Setup complete for ${HPC_USER}."
echo "  venv:           ${VENV_DIR}"
echo "  beegfs temp:    ${BEEGFS_TEMP}"
echo "  env file:       ${DEV_INIT_DIR}/clarity_local_env.sh"
echo "  nnunet_results: ${nnUNet_results}"
echo "  totalseg cache: ${TOTALSEG_HOME_DIR}"
echo
echo "Next:"
echo "  1) cp dev/260701_init/clarity_local_env_overrides.sh.example dev/260701_init/clarity_local_env_overrides.sh"
echo "  2) cp dev/260701_init/slurm_s3_worker.env.example dev/260701_init/slurm_s3_worker.env  # add AWS keys/profile"
echo "  3) sbatch dev/260701_init/slurm_s3_worker.job"
echo

export TORCH_VARIANT="${TORCH_VARIANT:-}"
"${PYTHON_BIN}" - <<'PY'
import os
import sys
import torch

print(
    "PyTorch:",
    torch.__version__,
    "| cuda build:",
    torch.version.cuda,
    "| cuda available now:",
    torch.cuda.is_available(),
)
tv = os.environ.get("TORCH_VARIANT", "")
if tv.startswith("cu") and sys.platform == "linux":
    if torch.version.cuda is None:
        print(
            "ERROR: torch is still CPU-only (+cpu). Re-run with CLARITY_PYTORCH_CUDA="
            + tv,
            file=sys.stderr,
        )
        sys.exit(1)
PY
